# Basic types and constructions in Python

## 1. Basic types: numeric types

In [ ]:
# int
num = 5
print(num)
print(type(num))

In [ ]:
# float
num = 13.4
print(num)

num = 1.5e2
print(type(num))

In [ ]:
# Python may convert types
num = int(num)
print(num, type(num))

num = float(num)
print(num, type(num))

## 2. Basic types: **logical types**

In [ ]:
# bool
print(3 > 4)
print(3 <= 3)
print(6 >= 6)
print(6 < 5)

In [ ]:
x=False  
y=True
print(x and y) # logical and
print(x or y) # logical or
print(not y) # logical not

In [ ]:
# example
x, y, z = True, False, True
result = x and y or z
print(result)

True


## 3. Basic types: string

In [ ]:
example_string = "Python course in ITMO"
print(example_string)
print(type(example_string))

Python course in ITMO
<class 'str'>


In [ ]:
example_string[7]

'c'

In [ ]:
# combine strings 
"You " + "can " + "just " + "add " + "one " + "string " + "to another "

In [ ]:
# slicing string
example_string = "Python cource in ITMO"
example_string[17:21]

'ITMO'

In [ ]:
# 'in' operator 
"3.14" in "Pi number = 3.1415926"

True

In [ ]:
example_string = "ITMO"
for letter in example_string:
    print("Letter", letter)

Letter I
Letter T
Letter M
Letter O


In [ ]:
# create string 
"{num} K ought to be enough for anybody. ({author})".format(
    num="ITMO", author="Bill Gates")

'ITMO K ought to be enough for anybody. (Bill Gates)'

## 4. Basic types: None object



In [ ]:
z = None
print(z)
print(type(z))

None
<class 'NoneType'>


# Collections in Python

## 1. Collections: list

In [ ]:
list0 = []

In [ ]:
saled_goods_count = [33450, 34010, 33990, 33200]

print(saled_goods_count)
print(type(saled_goods_count))

[33450, 34010, 33990, 33200]
<class 'list'>


In [ ]:
collections = ['list', 'tuple', 'dict', 'set']

print(collections)
print(type(collections))

['list', 'tuple', 'dict', 'set']
<class 'list'>


In [ ]:
features = ['Ivan Ivanovich', 'Medium', 500000, 12, True]
print (features)
print(type(features))

['Ivan Ivanovich', 'Medium', 500000, 12, True]
<class 'list'>


In [ ]:
# list length
len(collections)

4

In [ ]:
# indexes and slices
print(collections)

print(collections[0])
print(collections[-1])

['list', 'tuple', 'dict', 'set']
list
set


In [ ]:
range_list = list(range(5,10))
print(range_list)

[5, 6, 7, 8, 9]


In [ ]:
range_list[1:3]

[6, 7]

In [ ]:
range_list[3:]

[8, 9]

In [ ]:
range_list[:5]

[5, 6, 7, 8, 9]

In [ ]:
range_list[::2]

[5, 7, 9]

In [ ]:
range_list[::-1]

[9, 8, 7, 6, 5]

In [ ]:
# iterations
collections = ['list', 'tuple', 'dict', 'set']

for collection in collections:
    print('Learning {}...'.format(collection))

Learning list...
Learning tuple...
Learning dict...
Learning set...


In [ ]:
for idx, collection in enumerate(collections):
    print('#{} {}'.format(idx, collection))

#0 list
#1 tuple
#2 dict
#3 set


In [ ]:
# add or remove elements
collections.append('OrderedDict')

print(collections)

['list', 'tuple', 'dict', 'set', 'OrderedDict']


In [ ]:
collections.extend(['ponyset', 'unicorndict'])

print(collections)

['list', 'tuple', 'dict', 'set', 'OrderedDict', ['ponyset', 'unicorndict'], 'ponyset', 'unicorndict']


In [ ]:
collections += [None]

print(collections)

['list', 'tuple', 'dict', 'set', 'OrderedDict', 'ponyset', 'unicorndict', None]


In [ ]:
del collections[4]

print(collections)

['list', 'tuple', 'dict', 'set', ['ponyset', 'unicorndict'], 'ponyset', 'unicorndict']


In [ ]:
# min, max. sum
numbers = [4, 17, 19, 9, 2, 6, 10, 13]

print(min(numbers))
print(max(numbers))
print(sum(numbers))

2
19
80


## 2. Collections: tuple

In [ ]:
empty_tuple = ()
empty_tuple = tuple()

In [ ]:
immutables = (int, str, tuple)

In [ ]:
one_element_tuple = (1,)
guess_what = (1)

type(guess_what)

## 3. Collections: dictionary


In [ ]:
empty_dict = {}
empty_dict = dict()

collections_map = {
    'mutable': ['list', 'set', 'dict'],
    'immutable': ['tuple', 'frozenset']
}

In [ ]:
print(collections_map['immutable'])

['tuple', 'frozenset']


In [ ]:
# add elements
beatles_map = {
    'Paul': 'Bass',
    'John': 'Guitar',
    'George': 'Guitar',
}

print(beatles_map)

beatles_map['Ringo'] = 'Drums'

print(beatles_map)

{'Paul': 'Bass', 'John': 'Guitar', 'George': 'Guitar'}
{'Paul': 'Bass', 'John': 'Guitar', 'George': 'Guitar', 'Ringo': 'Drums'}


In [ ]:
# delete elements 
del beatles_map['John']


print(beatles_map)

{'Paul': 'Bass', 'George': 'Guitar', 'Ringo': 'Drums'}


In [ ]:
# itteration 
for key, value in beatles_map.items():
    print('{} — {}'.format(key, value))

Paul — Bass
George — Guitar
Ringo — Drums


## 4. Collections: set

In [ ]:
empty_set = set()
number_set = {1, 2, 3, 3, 3, 3, 4, 5}

print(number_set)

{1, 2, 3, 4, 5}


In [ ]:
odd_set, odd_set = set(), set()

odd_set = {1, 3, 5, 7}
even_set = {2, 4, 6, 8}

print(odd_set)
print(even_set)

union_set = odd_set | even_set
print(union_set)

intersection_set = odd_set & even_set
print(intersection_set)
for element in union_set:
  print(element)

## Where you can finde more informations about  Python

* https://www.coursera.org/courses?query=Python
* https://www.codeacademy.com
* http://www.pythontutor.ru
* http://www.learnpythonthehardway.org
* http://snakify.org
* https://www.checkio.org

# Numpy

## Numpy: arrays

### Basics 

In [ ]:
import numpy as np

In [ ]:
# array
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [ ]:
# float type array
b = np.array([1.5, 2.6, 3.1, 4.8, 5.0], dtype=float)
print(b)

[1.5 2.6 3.1 4.8 5. ]


In [ ]:
# boolean type array
c = np.array([True, False, True], dtype=bool)
print(c)

[ True False  True]


In [ ]:
#another way to create numpy array
d = np.arange(start=10, stop=20, step=1) 
print(d)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
# numpy array is 1D 
print(c.ndim)

1


In [ ]:
# operations 
print(a)
print(b)
print(a + b) # sum
print(a - b) # diff
print(a*b)   # multiply

[1 2 3 4 5]
[1.5 2.6 3.1 4.8 5. ]
[ 2.5  4.6  6.1  8.8 10. ]
[-0.5 -0.6 -0.1 -0.8  0. ]
[ 1.5  5.2  9.3 19.2 25. ]


###Norms of vector

**p-norm**

Let p ≥ 1 be a real number. The 
p-norm of vector $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ is

$$
\left\Vert x \right\Vert_{p} = \left( \sum_{i=1}^n \left| x_{i} \right|^{p} \right)^{1 / p},~p \geq 1.
$$

For p = 1 we get the taxicab norm, for p = 2 we get the Euclidean norm

In [ ]:
from numpy.linalg import norm

**Taxicab norm or Manhattan norm**
$$
 \left\Vert x \right\Vert_{1} = \sum_{i=1}^n \left| x_{i} \right|.
$$

In [ ]:
a = np.array([1, 2, -3])
print('L1 norm of vector a: {norm}'.format(norm = norm(a, ord=1)))

L1 norm of vector a: 6.0


**Euclidean norm**
$$
 \left\Vert x \right\Vert_{2} = \sqrt{\sum_{i=1}^n \left( x_{i} \right)^2}.
$$

In [ ]:
print('L2 norm of vector a: {norm}'.format(norm = norm(a, ord=2)))

L2 norm of vector a: 3.7416573867739413


###Distance between arrays

For two arrays $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ и $y = (y_{1}, \dots, y_{n}) \in \mathbb{R}^{n}$ $\ell_{1}$ and $\ell_{2}$  distance is calculated as:
$$
 \rho_{1}\left( x, y \right) = \left\Vert x - y \right\Vert_{1} = \sum_{i=1}^n \left| x_{i} - y_{i} \right|
$$

$$
 \rho_{2}\left( x, y \right) = \left\Vert x - y \right\Vert_{2} = 
 \sqrt{\sum_{i=1}^n \left( x_{i} - y_{i} \right)^2}.
$$

In [ ]:
b = np.array([1, 246, -565])
print('L1 distance between a and b: {dist}'.format(dist = norm(a - b, ord=1)))

L1 distance between a and b: 806.0


In [ ]:
print('L2 distance between a and b: {dist}'.format(dist = norm(a - b, ord=2)))

L2 distance between a and b: 612.6826258349424


###Scalar product

Scallar dot in $\mathbb{R}^{n}$ of two vectors $x = (x_{1}, \dots, x_{n})$ и $y = (y_{1}, \dots, y_{n})$ is:

$$
\langle x, y \rangle = \sum_{i=1}^n x_{i} y_{i}.
$$

In [ ]:
print('Scalar dot of a and b: {dot}'.format(dot = np.dot(a, b)))

Scalar dot of a and b: 2188


In [ ]:
# another way
print('Scalar dot of a and b: {dot}'.format(dot = a.dot(b)))

Scalar dot of a and b: 60.2


## Numpy: matrix

### Basics

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1, 2, 3], [2, 5, 6], [6, 7, 4]])
print(a)

[[1 2 3]
 [2 5 6]
 [6 7 4]]


In [ ]:
# more examples
b = np.eye(5)
print(b)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
c = np.ones((7, 5))
print(c)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
v = np.arange(0, 24, 2)
print(v)
d = v.reshape((3, 4))
print(d)

[ 0  2  4  6  8 10 12 14 16 18 20 22]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [ ]:
# indexes
print(d)
print(d[2, 1])
print(d[1, :])
print(d[:, 3])

### Matrix and vectors multiplication

In [ ]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])
r1 = np.dot(a, b)
r2 = a.dot(b)

In [ ]:
print('Matrix a:\n', a)
print('Matrix b:\n', b)
print('Multiplication, 1 method:\n', r1)
print('Multiplication, 2 method:\n', r2)

Matrix a:
 [[1 0]
 [0 1]]
Matrix b:
 [[4 1]
 [2 2]]
Multiplication, 1 method:
 [[4 1]
 [2 2]]
Multiplication, 2 method:
 [[4 1]
 [2 2]]


In [ ]:
c = np.array([1, 2, 3])
r3 = b.dot(c)

ValueError: ignored

In [ ]:
print('Matrix a:\n', a)
print('Vector c:\n', c)
print('Multiplication:\n', r3)

### Transposition

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.transpose(a)
c = a.T

In [ ]:
print('Matrix a:\n', a)
print('Transposed matrix:\n', b)
print('Transposed matrix:\n', c)

Matrix a:
 [[1 2]
 [3 4]]
Transposed matrix:
 [[1 3]
 [2 4]]
Transposed matrix:
 [[1 3]
 [2 4]]


### Determinant

In [ ]:
a = np.array([[1, 2, 1], [1, 1, 4], [2, 3, 6]], dtype=np.float32)
det = np.linalg.det(a)

In [ ]:
print('Matrix a:\n', a)
print('Determinant of a:\n', det)

### Rank

In [ ]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 2, 2]])
r = np.linalg.matrix_rank(a)

In [ ]:
print('Matrix a:\n', a)
print('Rank of a:\n', r)

In [ ]:
# check if systems of vectors is linearly independent
a = np.array([1, 2, 3])
b = np.array([1, 1, 1])
c = np.array([2, 3, 5])
m = np.array([a, b, c])

print(np.linalg.matrix_rank(m) == m.shape[0])

### System of linear equations

In [ ]:
a = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(a, b)


In [ ]:
print('Matrix a:\n', a)
print('Matrix b:\n', b)
print('Solution:\n', x)

Matrix a:
 [[3 1]
 [1 2]]
Matrix b:
 [9 8]
Solution:
 [2. 3.]


### Invertible matrix

In [ ]:
a = np.array([[1, 2, 1], [1, 1, 4], [2, 3, 6]], dtype=np.float32)
b = np.linalg.inv(a)

In [ ]:
print('Matrix a:\n', a)
print('Invertible matrix b:\n', b)
print('Identity matrix:\n', a.dot(b))

Matrix a:
 [[1. 2. 1.]
 [1. 1. 4.]
 [2. 3. 6.]]
Invertible matrix b:
 [[ 6.  9. -7.]
 [-2. -4.  3.]
 [-1. -1.  1.]]
Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Pandas

## Basics

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
# read csv file

df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/lab1/RegularSeasonCompactResults.csv')

In [ ]:
df

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0         1985      20   1228      81   1328      64    N      0
1         1985      25   1106      77   1354      70    H      0
2         1985      25   1112      63   1223      56    H      0
3         1985      25   1165      70   1432      54    H      0
4         1985      25   1192      86   1447      74    H      0
...        ...     ...    ...     ...    ...     ...  ...    ...
145284    2016     132   1114      70   1419      50    N      0
145285    2016     132   1163      72   1272      58    N      0
145286    2016     132   1246      82   1401      77    N      1
145287    2016     132   1277      66   1345      62    N      0
145288    2016     132   1386      87   1433      74    N      0

[145289 rows x 8 columns]

In [ ]:
# see the first 5 rows 
df.head(10)

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228      81   1328      64    N      0
1    1985      25   1106      77   1354      70    H      0
2    1985      25   1112      63   1223      56    H      0
3    1985      25   1165      70   1432      54    H      0
4    1985      25   1192      86   1447      74    H      0
5    1985      25   1218      79   1337      78    H      0
6    1985      25   1228      64   1226      44    N      0
7    1985      25   1242      58   1268      56    N      0
8    1985      25   1260      98   1133      80    H      0
9    1985      25   1305      97   1424      89    H      0

In [ ]:
# see the last 5 rows 
df.tail(5)

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
145284    2016     132   1114      70   1419      50    N      0
145285    2016     132   1163      72   1272      58    N      0
145286    2016     132   1246      82   1401      77    N      1
145287    2016     132   1277      66   1345      62    N      0
145288    2016     132   1386      87   1433      74    N      0

In [ ]:
# see the dimensions of the dataframe 
df.shape

(145289, 8)

In [ ]:
# extract all the column names as a list
df.columns.tolist()

['Season', 'Daynum', 'Wteam', 'Wscore', 'Lteam', 'Lscore', 'Wloc', 'Numot']

In [ ]:
# see statistics like mean, min, etc about each column of the dataset
df.describe()

Season         Daynum  ...         Lscore          Numot
count  145289.000000  145289.000000  ...  145289.000000  145289.000000
mean     2001.574834      75.223816  ...      64.497009       0.044387
std         9.233342      33.287418  ...      11.380625       0.247819
min      1985.000000       0.000000  ...      20.000000       0.000000
25%      1994.000000      47.000000  ...      57.000000       0.000000
50%      2002.000000      78.000000  ...      64.000000       0.000000
75%      2010.000000     103.000000  ...      72.000000       0.000000
max      2016.000000     132.000000  ...     150.000000       6.000000

[8 rows x 7 columns]

In [ ]:
# get the maximum values of all columns
df.max()

Season    2016
Daynum     132
Wteam     1464
Wscore     186
Lteam     1464
Lscore     150
Wloc         N
Numot        6
dtype: object

In [ ]:
# get the max value for a particular column
df['Wscore'].max() # or mean(), median(), min(), argmax()

186

In [ ]:
# get frequency of each item in the column
print(len(df['Wscore'].unique()))
print(len(df['Wteam'].unique()))
print(len(df['Season'].unique()))

130
364
32


## Sorting Values

In [ ]:
# sorting the dataframe in increasing order for the scores of the losing team
df.sort_values('Lscore', ascending=False).head()

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
17867    1989      92   1258     181   1109     150    H      0
16853    1989      68   1258     162   1109     144    A      0
22074    1990      96   1261     148   1258     141    H      0
24970    1991      68   1258     186   1109     140    H      0
1126     1985      65   1424     142   1429     140    A      0

## Filtering Rows

In [ ]:
# find which entries are above 150
df[df['Lscore'] < 10].head(10)

Empty DataFrame
Columns: [Season, Daynum, Wteam, Wscore, Lteam, Lscore, Wloc, Numot]
Index: []

In [ ]:
# find out when the winning team scores more than 150 points and 
# when the losing team scores below 100.
df2 = df[(df['Wscore'] > 150) & (df['Lscore'] < 90)]
df2

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
12046    1988      40   1328     152   1147      84    H      0
28687    1992      54   1261     159   1319      86    H      0
52600    1998      33   1395     153   1410      87    H      0

## Grouping

In [ ]:
df2.to_excel("df2.xlsx")

In [ ]:
# get the mean Wscore of each Wteam
df.groupby('Wteam')['Wscore'].mean().head()

Wteam
1101    78.111111
1102    69.893204
1103    75.839768
1104    75.825944
1105    74.960894
Name: Wscore, dtype: float64

In [ ]:
# finds where how many times that specific team won at home, on the road, or at a neutral site
df.groupby('Wteam')['Wloc'].value_counts().head(9)

Wteam  Wloc
1101   H        12
       A         3
       N         3
1102   H       204
       A        73
       N        32
1103   H       324
       A       153
       N        41
Name: Wloc, dtype: int64

## Extracting rows and columns

In [ ]:
df2 = df[['Wscore', 'Lscore']].head()

In [ ]:
df2

Wscore  Lscore
0      81      64
1      77      70
2      63      56
3      70      54
4      86      74

In [ ]:
df.iloc[1:10, 1]

1    25
2    25
3    25
4    25
5    25
6    25
7    25
8    25
9    25
Name: Daynum, dtype: int64

In [ ]:
df[0:3]

In [ ]:
df.iloc[100:120,1:10]


## Other resources

Pandas has been around for a while and there are a lot of other good resources if you're still interested on getting the most out of this library.

http://pandas.pydata.org/pandas-docs/stable/10min.html
https://www.datacamp.com/community/tutorials/pandas-tutorial-dataframe-python
http://www.gregreda.com/2013/10/26/intro-to-pandas-data-structures/
https://www.dataquest.io/blog/pandas-python-tutorial/
https://drive.google.com/file/d/0ByIrJAE4KMTtTUtiVExiUGVkRkE/view
https://www.youtube.com/playlist?list=PL5-da3qGB5ICCsgW1MxlZ0Hq8LL5U3u9y